################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CPP_SRCS := 
C_SRCS := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
jni/hellocpp \
cocos2d/plugin/protocols/platform/android \
cocos2d/plugin/protocols \
cocos2d/plugin/plugins/twitter/proj.ios/FHSTwitterEngine/OAuthConsumer/Crytpo \
cocos2d/plugin/jsbindings/manual \
cocos2d/plugin/jsbindings/auto \
cocos2d/external/xxhash \
cocos2d/external/websockets/include/wp8/win32helpers \
cocos2d/external/unzip \
cocos2d/external/tinyxml2 \
cocos2d/external/jansson \
cocos2d/external/edtaa3func \
cocos2d/external/chipmunk/src \
cocos2d/external/chipmunk/src/constraints \
cocos2d/external/ConvertUTF \
cocos2d/external/Box2D/Rope \
cocos2d/external/Box2D/Dynamics \
cocos2d/external/Box2D/Dynamics/Joints \
cocos2d/external/Box2D/Dynamics/Contacts \
cocos2d/external/Box2D/Common \
cocos2d/external/Box2D/Collision \
cocos2d/external/Box2D/Collision/Shapes \
cocos2d/extensions/proj.wp8 \
cocos2d/extensions/proj.win32 \
cocos2d/extensions/physics-nodes \
cocos2d/extensions/cocos2dx-store/Soomla/jsb \
cocos2d/extensions/cocos2dx-store/Soomla/domain/virtualGoods \
cocos2d/extensions/cocos2dx-store/Soomla/domain/virtualCurrencies \
cocos2d/extensions/cocos2dx-store/Soomla/domain \
cocos2d/extensions/cocos2dx-store/Soomla/data \
cocos2d/extensions/cocos2dx-store/Soomla/PurchaseTypes \
cocos2d/extensions/cocos2dx-store/Soomla \
cocos2d/extensions/assets-manager \
cocos2d/extensions/GUI/CCScrollView \
cocos2d/extensions/GUI/CCEditBox \
cocos2d/extensions/GUI/CCControlExtension \
cocos2d/cocos/ui \
cocos2d/cocos/storage/local-storage \
cocos2d/cocos/renderer \
cocos2d/cocos/platform/wp8-xaml/cpp \
cocos2d/cocos/platform/wp8 \
cocos2d/cocos/platform/winrt \
cocos2d/cocos/platform/win32 \
cocos2d/cocos/platform/linux \
cocos2d/cocos/platform/desktop \
cocos2d/cocos/platform/apple \
cocos2d/cocos/platform/android/jni \
cocos2d/cocos/platform/android \
cocos2d/cocos/platform \
cocos2d/cocos/physics/chipmunk \
cocos2d/cocos/physics \
cocos2d/cocos/network \
cocos2d/cocos/math \
cocos2d/cocos/editor-support/spine \
cocos2d/cocos/editor-support/spine/proj.wp8 \
cocos2d/cocos/editor-support/cocostudio/proj.wp8 \
cocos2d/cocos/editor-support/cocostudio/WidgetReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/TextReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/TextFieldReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/TextBMFontReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/TextAtlasReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/SliderReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ScrollViewReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/PageViewReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/LoadingBarReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ListViewReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/LayoutReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ImageViewReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/CheckBoxReader \
cocos2d/cocos/editor-support/cocostudio/WidgetReader/ButtonReader \
cocos2d/cocos/editor-support/cocostudio \
cocos2d/cocos/editor-support/cocosbuilder/proj.wp8 \
cocos2d/cocos/editor-support/cocosbuilder \
cocos2d/cocos/deprecated \
cocos2d/cocos \
cocos2d/cocos/base \
cocos2d/cocos/audio/wp8 \
cocos2d/cocos/audio/winrt \
cocos2d/cocos/audio/win32 \
cocos2d/cocos/audio/openal \
cocos2d/cocos/audio/linux \
cocos2d/cocos/audio/android/jni \
cocos2d/cocos/audio/android \
cocos2d/cocos/3d \
cocos2d/cocos/2d \
cocos2d/build/winrt/Cocos2dShaderCompiler \
Classes \

